230320/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name="create"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/update/', views.update, name="update"),
]

230320/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # DB 변경되지 않고 Django에서 보여줄 형식 지정하는 것
    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

230320/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    
    context = {
        'articles':articles
    }
    
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    article = Article.objects.get(id=pk)
    
    context = {
        'article':article,
    }
    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    
    # DB에 새로운 Article 저장
    # Article.objects.create(title=title, content=content)

    article = Article(title=title, content=content)
    # ~~~~ 중간 처리 (유효성 검사 과정) ~~~~
    article.save()
        
    return redirect('articles:index')

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    
    return redirect('articles:index')

def edit(request, pk):
    article = Article.objects.get(pk=pk)

    context = {
        'article':article,
    }
        
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)

    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

230320/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>DETAIL</h1>
    <hr>

    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <p>글 생성시각 : {{article.created_at}}</p>
    <p>글 수정시각 : {{article.updated_at}}</p>

    <!--method : 방법(GET POST)-->
    <!--action : 목적지-->
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="DELETE">
    </form>
    <a href="{% url 'articles:edit' article.pk %}">수정</a>
    <a href="{% url 'articles:index' %}">Back</a>

{% endblock content %}

230320/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>글 수정</h1>
    <hr>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">제목 : </label>
        <input type="text" name="title" id="title" value="{{article.title}}">
        <br>
        <label for="content">내용 : </label>
        <input type="text" name="content" id="content" value="{{article.content}}">
        <br>
        <input type="submit">
    </form>
    <hr>
    <a href="{% url 'articles:index'%}">뒤로</a>

{% endblock content %}

230320/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>INDEX</h1>
    <a href="{% url 'articles:new' %}">작성하기</a>
    <hr>

    {% for article in articles %}
    <p>글 번호 : {{article.id}}</p>
    <p><a href="{% url 'articles:detail' article.pk %}">글 제목 : {{article.title}}</a></p>
    <p>글 내용 : {{article.content}}</p>
    <hr>
    {% endfor %}

{% endblock content %}

230320/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>글 작성</h1>
    <hr>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">제목 : </label>
        <input type="text" name="title" id="title">
        <br>
        <label for="content">내용 : </label>
        <input type="text" name="content" id="content">
        <br>
        <input type="submit">
    </form>

{% endblock content %}